on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  fleximod-test:
    runs-on: ubuntu-latest
    steps:
      - id: checkout-CESM
        uses: actions/checkout@v4
      - id: run-fleximod
        run: |
          pwd
          cd ${GITHUB_WORKDIR}/CESM
          ./bin/git-fleximod test
